__title__ = 'microblog'
__description__ = 'A Flask based microblog.'
__url__ = 'https://github.com/Napchat/microblog'
__version__ = '1.0'
__author__ = 'Shang Nan'
__author_email__ = 'shangnan543@163.com'
__license__ = 'MIT License'
__copyright__ = 'Copyright 2017 Shang Nan'
